CREATE TABLE IF NOT EXISTS product(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price BIGINT NOT NULL,
    qty BIGINT NOT NULL,
    description TEXT,
    image VARCHAR(100)
)ENGINE=INNODB;